import db from './db.js';

const DISTRICTS_STATIONS = {
  'AMBALA': ['AMBALA CANTT','AMBALA CITY','AMBALA SADAR','BALDEV NAGAR','BARARA','MAHESH NAGAR','MULLANA','NAGGAL','NARAINGARH','PANJOKHRA','PARAO AMBALA CANTT','SAHA','SECTOR-9 AMBALA CITY','SHAHZADPUR','WOMEN POLICE STATION NARAINGARH AMBALA','WOMEN POLICE STATION AMBALA'],
  'BHIWANI': ['BAWANI KHERA','BEHAL','BHIWANI CITY','BHIWANI CIVIL LINES','BHIWANI SADAR','BOND KALAN','DADRI CITY','DADRI SADAR','JUI KALAN PS BHIWANI','LOHARU','PS INDUSTRIAL AREA BHIWANI','SIWANI','TOSHAM','WOMEN POLICE STATION BHIWANI'],
  'CHARKHI DADRI': ['BADHRA','BOND KALAN','DADRI CITY','DADRI SADAR','JHOJHU KALAN','WOMEN POLICE STATION CHARKHI DADRI'],
  'FARIDABAD': ['ADARSH NAGAR','BALLABHGARH CITY','BALLABHGARH SADAR','BHUPANI','CHHANSA','DABUA','DHAUJ','FARIDABAD CENTRAL','FARIDABAD KOTWALI','FARIDABAD N.I.T.','FARIDABAD OLD','KHERIPUL','METRO POLICE STATION FARIDABAD','MUJESAR','PALLA','POLICE STATION B.P.T.P.','S.G.M. NAGAR','SARAI KHAWAJA','SARAN','SECTOR-8','SECTOR-17','SECTOR-31 FARIDABAD','SECTOR-58','SURAJ KUND','TIGAON','WOMEN POLICE STATION BALLABGARH','WOMEN POLICE STATION NIT FARIDABAD','WOMEN POLICE STATION FARIDABAD'],
  'FATEHABAD': ['BHATTU KALAN','BHUNA','CITY FATEHABAD','CITY RATIA','CITY TOHANA','JAKHAL','SADAR FATEHABAD','SADAR RATTIA','SADAR TOHANA','WOMEN POLICE STATION FATEHABAD'],
  'GURUGRAM': ['BADSHAHPUR','BAJGHERA','BHONDSI','BILASPUR GURUGRAM','CITY SOHANA','CIVIL LINES GURGAON','DLF','DLF PH-3RD','DLF PHASE-1','DLF-II','FURRUKH NAGAR','GURGAON CITY','GURGAON SADAR','INDUSTRIAL SECTOR-7 MANESAR','KHEDKI DAULA','MANESAR','METRO','NEW COLONY','PALAM VIHAR','PATAUDI','PS CYBER MANESAR','RAJENDRA PARK','SECTOR-37','SECTOR-50','SECTOR-53','SECTOR-9A','SECTOR-10','SECTOR-14 GURUGRAM','SOHNA','SUSHANT LOK','UDYOG VIHAR','WOMEN POLICE STATION GURGAON'],
  'HANSI': ['BASS','HANSI CITY','HANSI SADAR','NARNAUND','PS CYBER CRIME HANSI','WOMEN POLICE STATION HANSI'],
  'HISAR': ['ADAMPUR','AGROHA','AZAD NAGAR HISAR','BARWALA','CYBER CRIME POLICE STATION HISAR','HISAR CITY','HISAR CIVIL LINES','HISAR SADAR','HTM HISAR','UKLANA','URBAN ESTATE HISAR','WOMEN POLICE STATION HISSAR'],
  'JHAJJAR': ['ASAUDA','BADLI','BERI','CITY BAHADURGARH','CITY JHAJJAR','DUJANA','LINE PAR BAHADURGARH','MACHHROLI','PS CYBER JHAJJAR','SADAR BAHADURGARH','SADAR JHAJJAR','SAHLAWAS','SECTOR-06 BAHADURGARH','WOMEN POLICE STATION JHAJJAR','WOMEN PS BAHADURGARH JHAJJAR'],
  'JIND': ['ALEWA','CITY SAFIDON','CIVIL LINE JIND','GARHI','JIND CITY','JIND SADAR','JULANA','NARWANA CITY','NARWANA SADAR','PILLU KHERA','SAFIDON','UCHANA','WOMEN POLICE STATION JIND'],
  'KAITHAL': ['CHEEKA','CIVIL LINE KAITHAL','DHAND','GUHLA','KAITHAL CITY','KAITHAL SADAR','KALAYAT','PUNDRI','RAJAUND','SIWAN','TITRAM','WOMEN POLICE STATION KAITHAL'],
  'KARNAL': ['ASSANDH','BUTANA','CYBER CRIME POLICE STATION KARNAL','GHARAUNDA','INDRI','KARNAL CITY','KARNAL CIVIL LINES','KARNAL SADAR','KUNJPURA','MADHUBAN','MUNAK KARNAL','NIGDHU KARNAL','NISSING','RAM NAGAR KARNAL','TARAORI','WOMEN POLICE STATION KARNAL'],
  'KURUKSHETRA': ['BABAIN','CYBER CRIME POLICE STATION KURUKSHETRA','ISMAILABAD','JHANSA','LADWA','PEHOWA','SHAHABAD','THANESAR CITY','THANESAR SADAR','WOMEN POLICE STATION KURUKSHETRA'],
  'MAHENDERGARH': ['ATELI','CITY KANINA','CITY MAHENDERGARH','CITY NARNAUL','NANGAL CHAUDHRI','NIZAMPUR','SADAR KANINA','SADAR MAHENDERGARH','SADAR NARNAUL','SATNALI','WOMEN POLICE STATION NARNAUL'],
  'NUH': ['BICCHOR','CITY NUH','CITY TAURU','FEROZEPUR JHIRKA','NAGINA','PINANGWA','PS CITY PUNHANA','PS MOHAMMADPUR AHIR','PUNHANA','ROZKA MEO','SADAR NUH','SADAR TAURU','WOMEN POLICE STATION MEWAT'],
  'PALWAL': ['BAHIN','CAMP PALWAL','CHAND HUT','CITY PALWAL','GADPURI','HASSANPUR','HATHIN','HODAL','MUNDKATI','SADAR PALWAL','UTAWAR','WOMEN POLICE STATION PALWAL'],
  'PANCHKULA': ['CHANDIMANDIR','CYBER CRIME','KALKA','MANSA DEVI COMPLEX','PANCHKULA SECTOR-5','PINJORE','RAIPUR RANI','SECTOR-14 PANCHKULA','SECTOR-20','SECTOR-7 PANCHKULA','WOMEN POLICE STATION PANCHKULA'],
  'PANIPAT': ['BAPOLI','CHANDNIBAGH','CYBER CRIME POLICE STATION PANIPAT','INDUSTRIAL SECTOR 29 PANIPAT','ISRANA','MATLAUDA','MODEL TOWN PANIPAT','OLD INDUSTRIAL PANIPAT','PANIPAT CITY','PANIPAT SADAR','QUILLA PANIPAT','SAMALKHA','SANOLI','SECTOR 13/17 PANIPAT','TEHSIL CAMP PANIPAT','WOMEN POLICE STATION PANIPAT'],
  'REWARI': ['BAWAL','DHARUHERA','JATUSANA','KASOLA','KHOL','KOSLI','MODEL TOWN REWARI','RAMPURA','REWARI CITY','REWARI SADAR','ROHADAI','SEC-6 DHARUHERA','WOMEN POLICE STATION REWARI'],
  'ROHTAK': ['ARYA NAGAR ROHTAK','BAHUAKBARPUR','CYBER POLICE STATION ROHTAK','I.M.T. ROHTAK','KALANAUR','LAKHAN MAJRA','MEHAM','P.G.I.M.S. ROHTAK','PURANI SABZI MANDI ROHTAK','ROHTAK CITY','ROHTAK CIVIL LINES','ROHTAK SADAR','SAMPLA','SHIVAJI COLONY','URBAN ESTATE ROHTAK','WOMEN POLICE STATION ROHTAK'],
  'SIRSA': ['CITY MANDI DABWALI','CYBER CRIME POLICE STATION SIRSA','DABWALI SADAR','DING','ELLENABAD','KALAN WALI','NATHU SARAI CHOPTA','ODHAN','POLICE STATION CIVIL LINE SIRSA','RANIA','RORI','SIRSA CITY','SIRSA SADAR','WOMEN POLICE STATION SIRSA'],
  'SONIPAT': ['BAHALGARH','BARAUDA','CIVIL LINE SONIPAT','GANNAUR','GOHANA CITY','GOHANA SADAR','HSIDC BARHI','KHARKHODA','KUNDLI','MOOHANA','MURTHAL','RAI','SECTOR-27 SONIPAT','SONIPAT CITY','SONIPAT SADAR','WOMEN POLICE STATION SONIPAT'],
  'YAMUNANAGAR': ['BILASPUR','BURIA','CHHACHHRAULI','CHHAPAR','CYBER CRIME POLICE STATION YAMUNANAGAR','FARAKPUR','GANDHI NAGAR YAMUNANAGAR','JAGADDHRI SADAR','JAGADHRI CITY','JATHLANA','PRATAP NAGAR','RADAUR','SADHAURA','WOMEN POLICE STATION YAMUNA NAGAR','YAMUNA NAGAR CITY','YAMUNA NAGAR SADAR'],
  'DABWALI': ['BARAGUDHA', 'CITY MANDI DABWALI', 'DABWALI SADAR', 'KALAN WALI', 'ODHAN', 'RORI', 'WOMEN POLICE STATION DABWALI SIRSA'],
  'STATE CRIME BRANCH': ['NODAL CYBER CRIME POLICE STATION HARYANA'],
  'HSENB': [
    'HSENB POLICE STATION AMBALA', 'HSENB POLICE STATION FARIDABAD',
    'HSENB POLICE STATION GURUGRAM', 'HSENB POLICE STATION HISAR',
    'HSENB POLICE STATION JIND', 'HSENB POLICE STATION KARNAL',
    'HSENB POLICE STATION REWARI', 'HSENB POLICE STATION ROHTAK',
    'PS HSENB BHIWANI', 'PS HSENB CHARKHI DADRI', 'PS HSENB FATEHABAD',
    'PS HSENB JHAJJAR', 'PS HSENB KAITHAL', 'PS HSENB KURUKSHETRA',
    'PS HSENB MAHENDERGARH', 'PS HSENB NUH', 'PS HSENB PALWAL',
    'PS HSENB PANCHKULA', 'PS HSENB PANIPAT', 'PS HSENB SIRSA',
    'PS HSENB SONIPAT', 'PS HSENB YAMUNANAGAR',
  ],
  'HSNCB': [
    'HSNCB UNIT AMBALA', 'HSNCB UNIT BHIWANI', 'HSNCB UNIT FARIDABAD',
    'HSNCB UNIT FATEHABAD', 'HSNCB UNIT GURUGRAM', 'HSNCB UNIT HISAR',
    'HSNCB UNIT KARNAL', 'HSNCB UNIT KURUKSHETRA', 'HSNCB UNIT REWARI',
    'HSNCB UNIT ROHTAK', 'HSNCB UNIT SIRSA',
  ],
};

const IO_NAMES = [
  'Rajesh Kumar','Suresh Singh','Amit Sharma','Vikas Yadav','Rohit Verma',
  'Sandeep Chauhan','Pankaj Malik','Deepak Nain','Rakesh Hooda','Manoj Dahiya',
  'Vinod Kumar','Kuldeep Singh','Harish Dewan','Satish Garg','Naresh Dhull',
  'Ramesh Saini','Ajay Rana','Sanjay Bishnoi','Naveen Arora','Pradeep Goel',
];

function toUsername(district, station, num) {
  const d = district.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '').slice(0, 8);
  const s = station.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '').slice(0, 25);
  return `io_${d}_${s}_${num}`;
}

const insertStmt = db.prepare(`
  INSERT INTO profiles (id, username, password, role, full_name, badge_number, rank, station_id, status)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'active')
`);

let created = 0;
let skipped = 0;
let nameIdx = 0;

const seedTx = db.transaction(() => {
  for (const [district, stations] of Object.entries(DISTRICTS_STATIONS)) {
    for (const station of stations) {
      for (let n = 1; n <= 2; n++) {
        const username = toUsername(district, station, n);

        const existing = db.prepare('SELECT id FROM profiles WHERE username = ?').get(username);
        if (existing) { skipped++; continue; }

        const rand = Math.random().toString(36).slice(2, 6);
        const id = `io-${district.slice(0,3).toLowerCase().replace(/[^a-z]/g,'')}-${rand}-${n}`;
        const name = IO_NAMES[nameIdx % IO_NAMES.length];
        nameIdx++;
        const badgeNo = `IO-${district.slice(0,3).toUpperCase().replace(/[^A-Z]/g,'')}-${n.toString().padStart(3,'0')}`;

        insertStmt.run(id, username, 'io123', 'io', name, badgeNo, 'Sub-Inspector (SI)', station);
        created++;
      }
    }
  }
});

seedTx();

console.log(`\n✅ Done!`);
console.log(`   Created : ${created} IO accounts (2 per station)`);
console.log(`   Skipped : ${skipped} (already exist)`);
console.log(`\n📋 Default password for all IOs: io123`);
console.log(`   Usernames follow pattern: io_<district>_<station>_1 / _2`);
